<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ9IAfjW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ9IAfjW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ9IAfjW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ9IAfjW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ9IAfjW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J9IAfjW',
    'container.build_id' => '49ed876a',
    'container.build_time' => 1557961995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ9IAfjW');
